//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int rental_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> game_id { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public Nullable<System.DateTime> rented_on { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Game Game { get; set; }
    }
}
